service: openai-streaming-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DEFAULT_MODEL: ${env:DEFAULT_MODEL, 'gpt-4-turbo-preview'}
    REQUEST_TIMEOUT: ${env:REQUEST_TIMEOUT, '60000'}
    CORS_ORIGINS: ${env:CORS_ORIGINS, '*'}
    RATE_LIMIT_WINDOW_MS: ${env:RATE_LIMIT_WINDOW_MS, '900000'}
    RATE_LIMIT_MAX: ${env:RATE_LIMIT_MAX, '100'}
  
  # API Gateway configuration
  httpApi:
    cors: true

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'

package:
  individually: true
  patterns:
    - '!node_modules/.cache/**'
    - '!test/**'
    - '!.env*'
    - '!.git/**'
    - '!.github/**'
    - '!.vscode/**'
    - '!logs/**'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000